const unitWeight = ['LB','KG','GR','Hundredths Pounds','MG','Tons','OZ'];
const unitWattage = ['Watt','Hours','Picowatts','Milliamp Hours', 'Milliwatts', 'Microwatts','Kilowatt Hours','Kilowatts','Nanowatts','Watts'];
const unitMemory = ['MB','GB','TB'];
const unitLength = ['FT','CM','MM','DM','Picometre','µM','M','Miles','Yards','Mils','IN','Nanometre','Hundredths-Inches','Kilometres','Angstrom'];
const unitCapacity = ['liters', 'Quarts' ,'Fluid Ounces', 'ounces', 'milliliters', 'Cubic Feet', 'Microliters', 'Cubic Centimeters' ,'Pints' ,'Gallons', 'pounds' ,'Tons','Cubic Inches', 'kilograms'];
const unitVolume = [];

const categories= {
    'Electronics':{
        'Audio' : [
            {'name':'Color','type':'text','example':'Red,Blue'}
        ],
        'Camera and Camcorder' : [
            {'name':'Size','type':'text','example':'Small'},
            {'name':'Compact','type':'text','example':''}, 
            {'name':'Number of Items','type':'number','example':'Small'}, 
            {'name':'Full-Size','type':'text','example':'Small'}, 
            {'name':'Color','type':'text','example':'Small'}, 
            {'name':'stylename','type':'text','example':'Small'}
        ],
        'Computer Peripheral' : [
            {'name':'Size','type':'text','example':''}, 
            {'name':'Color','type':'text','example':''}, 
            {'name':'stylename','type':'text','example':''}
        ],

        'Desktop and Laptop' : [
            {'name':'Item Weight','unit':unitWeight,'type':'text','example':''},
            {'name':'Number of Items','type':'number','example':''},
            {'name':'Wattage','unit':unitWattage,'type':'text','example':''}, 
            {'name':'Voltage','type':'text','example':''}, 
            {'name':'Team Name','type':'text','example':''}, 
            {'name':'Item Display weight','unit':unitWeight,'type':'text','example':''},
            {'name':'Color','type':'text','example':''},
            {'name':'Memory Storage Capacity','unit':unitMemory,'type':'text','example':''},
            {'name':'Model Number','type':'text','example':''},
            {'name':'Product Grade','type':'text','example':''},
            {'name':'Hardware Platform','type':'text','example':''},
            {'name':'Hard Drive Size','unit':unitMemory,'type':'text','example':''},
            {'name':'Screen Size','unit':['FT','CM','MM','DM','Picometre','µM','M','Miles','Yards','Mils','IN','Nanometre','Hundredths-Inches','Kilometres','Angstrom'],'type':'text','example':''},
        ],
        'Earphone' : [
            {'name':'Size','type':'text','example':''},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Edition','type':'text','example':''},
        ],
        'Gaming' : [
            {'name':'Item Weight','type':'text','example':''},
            {'name':'Number of Items','type':'numberer','example':''},
            {'name':'Wattage','unit':unitWattage,'type':'text','example':''},
            {'name':'Model Number','type':'number','example':''},
        ],
        'Headphone' : [
            {'name':'Size','type':'text','example':''},
            {'name':'Color','type':'text','example':''},
        ],
        'Mobile Phone' : [
            {'name':'Memory','unit':unitMemory,'type':'text','example':''},
            {'name':'Item Weight','unit':unitWeight,'type':'text','example':''},
            {'name':'Number of Items','type':'numberer','example':''},
            {'name':'Team Name','type':'text','example':''},
            {'name':'Model Number','type':'number','example':''},
            {'name':'Color','type':'text','example':''},
            {'name':'Product Grade','type':'text','example':''},
            {'name':'Screen Size Unit Of Measure','unit':unitLength,'type':'text','example':''},
        ],
        'Mobile Accessories' : [
            {'name':'Pattern','type':'text','example':''},
            {'name':'Color','type':'text','example':''},
            {'name':'Number of Items','type':'numberer','example':''},
            {'name':'Material Type','type':'text','example':''},
            {'name':'Item Weight','unit':unitWeight,'type':'text','example':''},
            {'name':'Thickness','unit':unitLength,'type':'text','example':''},
            {'name':'Model Number','type':'number','example':''},
            {'name':'Screen Size Unit Of MeasureScreen','unit':unitLength,'type':'text','example':''},
        ],
        'Safety Security' : [
            {'name':'Style Name','type':'text','example':''},
            {'name':'Size','type':'text','example':''},
            {'name':'Number of Items','type':'numberer','example':''},
            {'name':'Item Form','type':'text','example':''},
            {'name':'Color','type':'text','example':''},
            {'name':'Pattern','type':'text','example':''},
            {'name':'Display Weight','unit':unitWeight,'type':'text','example':''},
        ],
        'Smart Watches' : [
            {'name':'Size','type':'text','example':''},
            {'name':'Style','type':'text','example':''},
            {'name':'Number of Items','type':'numberer','example':''},
            {'name':'Item Form','type':'text','example':''},
            {'name':'Color','type':'text','example':''},
            {'name':'DriveMemory Storage Capacity','unit':unitMemory,'type':'text','example':''},
            {'name':'Model Number','unit':unitWeight,'type':'text','example':''},
            {'name':'Manufacturer Part Number','type':'text','example':''},
            {'name':'Unit Count','type':'text','example':''},
            {'name':'Band Colour','type':'text','example':''},
            {'name':'Shape','type':'text','example':''},
            {'name':'Screen Size Unit Of MeasureScreen','unit':unitLength,'type':'text','example':''},
        ],
        'Speaker' : [
            {'name':'Color','type':'text','example':''},
        ],
        'Television' : [
            {'name':'Style','type':'text','example':''},
            {'name':'DriveMemory Storage Capacity','unit':unitMemory,'type':'text','example':''},
            {'name':'Item Weight','unit':unitWeight,'type':'text','example':''},
            {'name':'Number of Items','type':'numberer','example':''},
            {'name':'Model Number','type':'text','example':''},
            {'name':'Manufacturer Part Number','type':'text','example':''},
            {'name':'Wattage','unit':unitWattage,'type':'text','example':''},
            {'name':'Unit Count','type':'text','example':''},
            {'name':'Voltage','type':'text','example':''},
            {'name':'Team Name','type':'text','example':''},
            {'name':'Color','type':'text','example':''},
            {'name':'Display Size','type':'text','example':''},
        ],
        'Video' : [
            {'name':'Style Name','type':'text','example':''},
            {'name':'Size','type':'text','example':''},
            {'name':'Color','type':'text','example':''},
        ],
        'Air Conditioning and Air Cleaners' : [
            {'name':'Style','type':'text','example':''},
            {'name':'Size','type':'text','example':''},
            {'name':'Number of Items','type':'numberer','example':''},
            {'name':'Item Weight','unit':unitWeight,'type':'text','example':''},
            {'name':'Wattage','unit':unitWattage,'type':'text','example':''},
            {'name':'Voltage','type':'text','example':''},
            {'name':'Unit Count','type':'text','example':''},
            {'name':'Model','type':'text','example':''},
        ],
        'Health, Home and Personal Care' : [
            {'name':'Item Display Length','type':'text','example':''},
            {'name':'Size','type':'text','example':''},
            {'name':'Number of Items','type':'numberer','example':''},
            {'name':'Material Type','type':'text','example':''},
            {'name':'Package Type','type':'text','example':''},
            {'name':'Item Display','type':'text','example':''},
            {'name':'Width','type':'text','example':'','unit':unitLength},
            {'name':'Patter','type':'text','example':''},
            {'name':'Color','type':'text','example':''},
            {'name':'Item Display Height','type':'text','example':''},
            {'name':'Item Display Diameter','type':'text','example':''},
            {'name':'Item Weight','type':'text','example':''},
            {'name':'model','type':'text','example':''},
            {'name':'Manufacturer Part Number','type':'number','example':''},
            {'name':'Wattage','type':'text','example':'','unit':unitWattage},
            {'name':'Unit Count','type':'text','example':''},
            {'name':'Shape','type':'text','example':''},
        ],
        'Heaters' : [
            {'name':'Size','type':'text','example':''},
            {'name':'Style','type':'text','example':''},
            {'name':'Number of Items','type':'number','example':''},
            {'name':'Item Weight','type':'text','example':'','unit':unitWeight},
            {'name':'Wattage','type':'text','example':'','unit':unitWattage},
            {'name':'Voltage','type':'text','example':''},
            {'name':'model','type':'text','example':''},
            {'name':'Unit Count','type':'number','example':''},
        ],
        'Kitchen Appliances' : [
            {'name':'Size','type':'text','example':'Large'},
            {'name':'Material Type','type':'text','example':'Steel'},
            {'name':'Number of Items','type':'number','example':'2,3'},
            {'name':'Color','type':'text','example':''},
            {'name':'Item Weight','type':'text','example':'3.3','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'1'},
        ],
        'Lighting & Electric Fans' : [
            {'name':'Size','type':'text','example':'Large'},
            {'name':'Style','type':'text','example':'Modern'},
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Item Weight','type':'text','example':'','unit':unitWeight},
            {'name':'Color','type':'text','example':''},
            {'name':'Material Type','type':'text','example':'Steel'},
            {'name':'Manufacturer Part Number','type':'text','example':''},
            {'name':'Model','type':'text','example':''},
            {'name':'Wattage','type':'text','example':'','unit':unitWattage},
            {'name':'Unit Count','type':'number','example':'5'},
            {'name':'Voltage','type':'number','example':'5'},
        ],
        'Refrigerators and Freezers' : [
            {'name':'Size','type':'text','example':''},
            {'name':'Style','type':'text','example':''},
            {'name':'Number of Items','type':'number','example':''},
            {'name':'Item Weight','type':'text','example':'4','unit':unitWeight},
            {'name':'Color','type':'text','example':''},
            {'name':'Material Type','type':'text','example':''},
            {'name':'Model','type':'text','example':''},
            {'name':'Capacity','type':'text','example':'','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'text','example':''},
            {'name':'Model','type':'text','example':'LG12'},
        ],
        'Vacuum Cleaners' : [
            {'name':'Size','type':'text','example':''},
            {'name':'Style','type':'text','example':''},
            {'name':'Number of Items','type':'number','example':''},
            {'name':'Item Weight','type':'text','example':'4','unit':unitWeight},
            {'name':'Color','type':'text','example':''},
            {'name':'Material Type','type':'text','example':''},
            {'name':'Model','type':'text','example':''},
            {'name':'Capacity','type':'text','example':'','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'text','example':''},
            {'name':'Model','type':'text','example':'LG12'},
        ],
        'Washing Machines and Accessories' : [
            {'name':'Size','type':'text','example':''},
            {'name':'Style','type':'text','example':''},
            {'name':'Number of Items','type':'number','example':''},
            {'name':'Item Weight','type':'text','example':'4','unit':unitWeight},
            {'name':'Color','type':'text','example':''},
            {'name':'Material Type','type':'text','example':''},
            {'name':'Model','type':'text','example':''},
            {'name':'Capacity','type':'text','example':'','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'text','example':''},
            {'name':'Model','type':'text','example':'LG12'},
        ],
        'Water Purifiers and Coolers' : [
            {'name':'Size','type':'text','example':''},
            {'name':'Style','type':'text','example':''},
            {'name':'Number of Items','type':'number','example':''},
            {'name':'Item Weight','type':'text','example':'4','unit':unitWeight},
            {'name':'Color','type':'text','example':''},
            {'name':'Material Type','type':'text','example':''},
            {'name':'Model','type':'text','example':''},
            {'name':'Capacity','type':'text','example':'','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'text','example':''},
            {'name':'Model','type':'text','example':'LG12'},
        ]
    },
    'Grocery':{
        'Fruits and Vegetables':[
        ],
        'Masala & Seasoning':[
        ],
        'Oil & Ghee':[
        ],
        'Gourmet & World Foods':[
        ],
        'Foodgrains':[
        ],
        'Eggs, Meat & Fish':[
        ],
        'Cleaning & Household':[
            {'name':'Size','type':'text','example':''}, 
            {'name':'Color','type':'text','example':''}, 
            {'name':'Style','type':'text','example':''},
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Material Type','type':'text','example':'plastic'},
            {'name':'Width Range','type':'text','example':'','unit':unitLength},
            {'name':'Length Range','type':'text','example':'','unit':unitLength},
        ],
        'Beverages':[
            {'name':'Size','type':'text','example':''}, 
            {'name':'Color','type':'text','example':''}, 
            {'name':'stylename','type':'text','example':''}
        ],
        'Beauty & Hygiene':[
            {'name':'Size','type':'text','example':''}, 
            {'name':'Color','type':'text','example':''}, 
            {'name':'Scent','type':'text','example':'rose'},
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'PPU Count','type':'text','example':'1'},
            {'name':'Item Form','type':'text','example':'Cream'},
            {'name':'Model','type':'text','example':'AB12'},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
        ],
        'Bakery, Cakes & Dairy':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Material Type','type':'text','example':'floor'},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Shape','type':'text','example':'Round'},
            {'name':'Capacity','type':'float','example':'4','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112'},
        ],
        'Kitchen Accessories':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Material Type','type':'text','example':'Steel'},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Pattern','type':'text','example':''},
        ],
        'Baby Care':[
            {'name':'Scent','type':'text','example':'rose'}, 
            {'name':'Scent','type':'text','example':'rose'}, 
            {'name':'Style','type':'text','example':'modern'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Material Type','type':'text','example':'rose'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'PPU Count','type':'text','example':'1'},
            {'name':'Item Form','type':'text','example':'Cream'},
            {'name':'Pattern','type':'text','example':''},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Model','type':'text','example':'AB-12'},
        ],
        'Snacks & Branded Foods':[
        ],
        'Pet Care':[
            {'name':'Scent Name','type':'text','example':'mild'}, 
            {'name':'Flavor','type':'text','example':''}, 
            {'name':'Color','type':'text','example':'brown'},
            {'name':'Number of Items','type':'number','example':'6'},
        ],
        'Stationery':[
            {'name':'Size','type':'text','example':'A4,6x4'}, 
            {'name':'Paper Size','type':'text','example':''}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Line Size','type':'text','example':''} ,
            {'name':'Maximum Size','type':'text','example':''} ,
        ],
    },
    'Home Decor':{
        'Home Decor':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Style','type':'text','example':'modern'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Material Type','type':'text','example':'wood'},
            {'name':'Pattern','type':'text','example':'Sripped'}, 
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Wattage','type':'text','example':'', 'unit':unitWattage}, 
            {'name':'VoltageColor','type':'text','example':'6'}, 
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Shape','type':'text','example':'Round'},
        ],
        'Home Furnishings':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Style','type':'text','example':'modern'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Material Type','type':'text','example':'wood'},
            {'name':'Pattern','type':'text','example':'Sripped'}, 
            {'name':'Display Weight','type':'text','example':'5','unit':unitWeight},
        ],
        'Furniture':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Style','type':'text','example':'modern'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Material Type','type':'text','example':'wood'},
            {'name':'Pattern','type':'text','example':'Sripped'}, 
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Team Name','type':'text','example':'chennai super kings'}, 
            {'name':'Shape','type':'text','example':'Round'},
        ],
        'Garden and Outdoor Products':[
            {'name':'Material Type','type':'text','example':'wood'},
            {'name':'Color','type':'text','example':''}, 
        ],
        'Home Improvement':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Style','type':'text','example':'modern'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Color','type':'text','example':''}, 
        ],
        'Cookware and Dining':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Material Type','type':'text','example':'wood'},
            {'name':'Pattern','type':'text','example':'Sripped'}, 
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Shape','type':'text','example':'Round'},
            {'name':'Capacity','type':'text','example':'', 'unit':unitCapacity}, 
            {'name':'Manufacturer Part Number','type':'float','example':'A-112'},
            {'name':'Color','type':'text','example':''}, 
        ],
        'Storage and Organisation':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Style','type':'text','example':'modern'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Material Type','type':'text','example':'wood'},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Team Name','type':'text','example':'Lions'},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Shape','type':'text','example':'Round'},
        ],
    },
    'Health and Wellness':{
        'Home Decor':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Material Type','type':'text','example':'floor'},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Shape','type':'text','example':'Round'},
            {'name':'Capacity','type':'float','example':'4','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112'},
        ],
        'Home Furnishings':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Material Type','type':'text','example':'floor'},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Shape','type':'text','example':'Round'},
            {'name':'Capacity','type':'float','example':'4','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112'},
        ],
        'Furniture':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Material Type','type':'text','example':'floor'},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Shape','type':'text','example':'Round'},
            {'name':'Capacity','type':'float','example':'4','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112'},
        ],
        'Garden and Outdoor Products':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Material Type','type':'text','example':'floor'},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Shape','type':'text','example':'Round'},
            {'name':'Capacity','type':'float','example':'4','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112'},
        ],
        'Home Improvement':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Material Type','type':'text','example':'floor'},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Shape','type':'text','example':'Round'},
            {'name':'Capacity','type':'float','example':'4','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112'},
        ],
        'Cookware and Dining':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Material Type','type':'text','example':'floor'},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Shape','type':'text','example':'Round'},
            {'name':'Capacity','type':'float','example':'4','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112'},
        ],
        'Storage and Organisation':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Material Type','type':'text','example':'floor'},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Shape','type':'text','example':'Round'},
            {'name':'Capacity','type':'float','example':'4','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112'},
        ],
        'Home & Decor':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Material Type','type':'text','example':'floor'},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Shape','type':'text','example':'Round'},
            {'name':'Capacity','type':'float','example':'4','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112'},
        ],
    },
    'Beauty and Personal Care':{
        'Home Decor':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Material Type','type':'text','example':'floor'},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Shape','type':'text','example':'Round'},
            {'name':'Capacity','type':'float','example':'4','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112'},
        ],
        'Home Furnishings':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Material Type','type':'text','example':'floor'},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Shape','type':'text','example':'Round'},
            {'name':'Capacity','type':'float','example':'4','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112'},
        ],
        'Furniture':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Material Type','type':'text','example':'floor'},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Shape','type':'text','example':'Round'},
            {'name':'Capacity','type':'float','example':'4','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112'},
        ],
        'Garden and Outdoor Products':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Material Type','type':'text','example':'floor'},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Shape','type':'text','example':'Round'},
            {'name':'Capacity','type':'float','example':'4','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112'},
        ],
        'Home Improvement':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Material Type','type':'text','example':'floor'},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Shape','type':'text','example':'Round'},
            {'name':'Capacity','type':'float','example':'4','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112'},
        ],
        'Cookware and Dining':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Material Type','type':'text','example':'floor'},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Shape','type':'text','example':'Round'},
            {'name':'Capacity','type':'float','example':'4','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112'},
        ],
        'Storage and Organisation':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Material Type','type':'text','example':'floor'},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Shape','type':'text','example':'Round'},
            {'name':'Capacity','type':'float','example':'4','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112'},
        ],
        'Home & Decor':[
            {'name':'Size','type':'text','example':'small'}, 
            {'name':'Number of Items','type':'number','example':'6'},
            {'name':'Color','type':'text','example':''}, 
            {'name':'Material Type','type':'text','example':'floor'},
            {'name':'Item Weight','type':'text','example':'5','unit':unitWeight},
            {'name':'Unit Count','type':'number','example':'6'},
            {'name':'Model','type':'text','example':'AB-12'},
            {'name':'Shape','type':'text','example':'Round'},
            {'name':'Capacity','type':'float','example':'4','unit':unitCapacity},
            {'name':'Manufacturer Part Number','type':'float','example':'A-112'},
        ],
    },
    'Food and Beverages':{

    }
};

export default categories;
